name: Local Config
version: 1.0.0
schema: v1
models:
  - name: DeepSeek Coder 6.7B
    provider: ollama
    model: deepseek-coder:6.7b
    roles:
      - chat
      - edit
      - apply
  - name: Qwen2.5-Coder 1.5B
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles:
      - autocomplete
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
